version: "3"
services:
  product_service:
    build: ./ProductService
    ports:
      - "3002:3000"
    environment:
      - SERVER_NAME=product_service
    depends_on:
      - redis

  product_service_backup:
    build: ./ProductService
    ports:
      - "3003:3000"
    environment:
      - SERVER_NAME=product_service_backup
    depends_on:
      - redis

  nginx:
    build: ./nginx
    ports:
      - "8080:80"
    depends_on:
      - product_service
      - product_service_backup

  user_service:
    build: ./UserService
    ports:
      - "3001:3001"
    depends_on:
      - redis

  order_service:
    build: ./OrderService
    ports:
      - "3002:3002"
    environment:
      - SERVER_NAME=order_service
      
  redis:
    image: redis:latest
    ports:
      - "6379:6379"